// <auto-generated />
using System;
using EcfrApi.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcfrApi.Web.Migrations
{
    [DbContext(typeof(EcfrDbContext))]
    partial class EcfrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("EcfrApi.Web.Models.TitleVersionCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checksum")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("XmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TitleNumber", "IssueDate")
                        .IsUnique();

                    b.ToTable("TitleVersions");
                });

            modelBuilder.Entity("EcfrApi.Web.Models.TitleWordCountCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TitleNumber", "Date")
                        .IsUnique();

                    b.ToTable("TitleWordCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
