containers:
  - name: api
    image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Staging
      - name: ASPNETCORE_URLS
        value: http://+:80
      - name: ConnectionStrings__DefaultConnection
        secretRef: staging-connection-string
    resources:
      cpu: 2
      memory: 4Gi
    probes:
      - type: liveness
        httpGet:
          path: /api/health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
      - type: startup
        httpGet:
          path: /api/health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
    ingress:
      external: true
      targetPort: 80
      transport: http
      allowInsecure: false

scale:
  minReplicas: 1
  maxReplicas: 2
  rules:
    - name: http-rule
      http:
        metadata:
          concurrentRequests: "5"

networking:
  ingress:
    external:
      allowInsecure: false
    internal:
      allowInsecure: true
  restrictOutboundTraffic: false
