containers:
  - name: client
    image: ${REGISTRY_NAME}.azurecr.io/${CLIENT_IMAGE_NAME}:${GITHUB_SHA}
    resources:
      cpu: 0.5
      memory: 1Gi
    probes:
      - type: liveness
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
    ingress:
      external: true
      targetPort: 80
      transport: http

  - name: api
    image: ${REGISTRY_NAME}.azurecr.io/${API_IMAGE_NAME}:${GITHUB_SHA}
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Production
      - name: ASPNETCORE_URLS
        value: http://+:80
    resources:
      cpu: 0.5
      memory: 1Gi
    probes:
      - type: liveness
        httpGet:
          path: /api/health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
    ingress:
      external: true
      targetPort: 80
      transport: http

scale:
  minReplicas: 1
  maxReplicas: 3
  rules:
    - name: http-rule
      http:
        metadata:
          concurrentRequests: "10"

networking:
  ingress:
    external:
      allowInsecure: false
    internal:
      allowInsecure: true
  restrictOutboundTraffic: false
