version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  client:
    build:
      context: ./ecfr-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
