name: Deploy to Azure

on:
  push:
    branches: [ "master" ]
    paths:
      - 'ecfr-client/**'
      - 'EcfrApi.Web/**'
      - '.github/workflows/**'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      deploy_client:
        description: 'Deploy client app'
        type: boolean
        default: true
      deploy_api:
        description: 'Deploy API'
        type: boolean
        default: true

env:
  AZURE_WEBAPP_NAME: ecfr-app
  REGISTRY_NAME: ecfrregistry
  API_IMAGE_NAME: ecfr-api
  CLIENT_IMAGE_NAME: ecfr-client

jobs:
  build-client:
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_client == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.filter.outputs.client_changed }}
    steps:
    - uses: actions/checkout@v3

    - name: Check for client changes
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          client_changed:
            - 'ecfr-client/**'
            - '.github/workflows/azure-deploy.yml'

    - name: Setup Node.js
      if: steps.filter.outputs.client_changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './ecfr-client/package-lock.json'

    - name: Cache node modules
      if: steps.filter.outputs.client_changed == 'true'
      uses: actions/cache@v3
      with:
        path: ecfr-client/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('ecfr-client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Angular dependencies
      if: steps.filter.outputs.client_changed == 'true'
      run: |
        cd ecfr-client
        npm ci

    - name: Build Angular app
      if: steps.filter.outputs.client_changed == 'true'
      run: |
        cd ecfr-client
        npm run build

  build-api:
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_api == 'true' }}
    uses: ./.github/workflows/dotnet.yml

  build-and-push-images:
    needs: [build-client, build-api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:latest
        buildkitd-flags: --debug

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push API image
      if: ${{ github.event_name == 'push' || github.event.inputs.deploy_api == 'true' }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=registry,ref=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:buildcache,mode=max

    - name: Build and push Client image
      if: ${{ github.event_name == 'push' || github.event.inputs.deploy_client == 'true' }}
      uses: docker/build-push-action@v4
      with:
        context: ./ecfr-client
        push: true
        tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CLIENT_IMAGE_NAME }}:${{ github.sha }}
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=registry,ref=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CLIENT_IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CLIENT_IMAGE_NAME }}:buildcache,mode=max

  deploy:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy API to Azure Container App
      if: ${{ github.event_name == 'push' || github.event.inputs.deploy_api == 'true' }}
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.REGISTRY_NAME }}
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        containerAppName: ${{ env.AZURE_WEBAPP_NAME }}-api
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppEnvironment: ecfr-env
        targetPort: 80
        ingress: external
        location: eastus
        image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
        cpu: 0.5
        memory: 1Gi
        minReplicas: 1
        maxReplicas: 3
        env: |
          - name: ASPNETCORE_ENVIRONMENT
            value: Production

    - name: Deploy Client to Azure Container App
      if: ${{ github.event_name == 'push' || github.event.inputs.deploy_client == 'true' }}
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/ecfr-client
        acrName: ${{ env.REGISTRY_NAME }}
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        containerAppName: ${{ env.AZURE_WEBAPP_NAME }}-client
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppEnvironment: ecfr-env
        targetPort: 80
        ingress: external
        location: eastus
        image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.CLIENT_IMAGE_NAME }}:${{ github.sha }}
        cpu: 0.5
        memory: 1Gi
        minReplicas: 1
        maxReplicas: 3
        env: |
          - name: API_HOST
            value: ${{ env.AZURE_WEBAPP_NAME }}-api.azurecontainerapps.io
