name: Deploy API to Azure

on:
  push:
    branches: [ "master" ]
    paths:
      - 'EcfrApi.Web/**'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      deploy_api:
        description: 'Deploy API'
        type: boolean
        default: true

env:
  AZURE_WEBAPP_NAME: ecfr-app
  REGISTRY_NAME: ecfrregistry
  API_IMAGE_NAME: ecfr-api

jobs:
  build-api:
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_api == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api_changed }}
    steps:
    - uses: actions/checkout@v4

    - name: Check for API changes
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          api_changed:
            - 'EcfrApi.Web/**'
            - 'Dockerfile'

    - name: Setup .NET
      if: steps.filter.outputs.api_changed == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      if: steps.filter.outputs.api_changed == 'true'
      run: dotnet restore

    - name: Build
      if: steps.filter.outputs.api_changed == 'true'
      run: dotnet build --no-restore

    - name: Test
      if: steps.filter.outputs.api_changed == 'true'
      run: dotnet test --no-build --verbosity detailed

  deploy-api:
    needs: build-api
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.deploy_api == 'true' }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        driver: docker-container

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:${{ github.sha }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy API to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: ${{ env.REGISTRY_NAME }}
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        containerAppName: ${{ env.AZURE_WEBAPP_NAME }}-api
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppEnvironment: ecfr-env
        targetPort: 80
        ingress: external
        location: eastus
        imageToDeploy: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
        environmentVariables: |
          ASPNETCORE_ENVIRONMENT=Production
